name: Pack Modpack
on:
  release: 
    types: published

jobs:
  pack:
    name: Pack Modpack
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Place version id in index.json
      run: sed -i 's/{{versionId}}/${{ github.event.release.tag_name }}/' modrinth.index.json
    - name: Pack modpack
      run: zip -r 'MC2026L-${{ github.event.release.tag_name }}.mrpack' modrinth.index.json overrides
    - name: Attach modpack to release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload '${{ github.event.release.tag_name }}' 'MC2026L-${{ github.event.release.tag_name }}.mrpack'